#pragma once
#include "x86/types.h"


namespace x86::vmx {

enum class exit_reason_t : uint16_t {
    exception_or_nmi = 0,
    external_interrupt = 1,
    triple_fault = 2,
    init_signal = 3,
    startup_ipi = 4,
    io_smm_interrupt = 5,
    other_smi = 6,
    interrupt_window = 7,
    nmi_windows = 8,
    task_switch = 9,
    cpuid = 10,
    getsec = 11,
    hlt = 12,
    invd = 13,
    invlpg = 14,
    rdpmc = 15,
    rdtsc = 16,
    rsm = 17,
    vmcall = 18,
    vmclear = 19,
    vmlaunch = 20,
    vmptrld = 21,
    vmptrst = 22,
    vmread = 23,
    vmresume = 24,
    vmwrite = 25,
    vmxoff = 26,
    vmxon = 27,
    cr_access = 28,
    mov_dr = 29,
    io = 30,
    rdmsr = 31,
    wrmsr = 32,
    vmentry_invalid_guest_state = 33,
    vmentry_msr_load_failure = 34,
    mwait = 36,
    monitor_trap_flag = 37,
    monitor = 39,
    pause = 40,
    vmentry_machine_check = 41,
    tpr_below_threshold = 43,
    apic_access = 44,
    virtualized_eoi = 45,
    access_gdtr_idtr = 46,
    access_ldtr_tr = 47,
    ept_violation = 48,
    ept_misconfiguration = 49,
    invept = 50,
    rdtscp = 51,
    vmx_preemption_timer_expired = 52,
    invvpid = 53,
    wbinvd = 54,
    xsetbv = 55,
    apic_write = 56,
    rdrand = 57,
    invpcid = 58,
    vmfunc = 59,
    encls = 60,
    rdseed = 61,
    page_mod_log_full = 62,
    xsaves = 63,
    xrstors = 64,
};

}
