#pragma once

#include "types.h"

namespace x86::opcode {

enum class mode_t {
    real_mode,
    protected_mode,
    long_mode
};

enum class instruction_t {
    aaa,
    aad,
    aam,
    aas,
    adc,
    adcx,
    add,
    addpd,
    addps,
    addsd,
    addss,
    addsubpd,
    addsubps,
    adox,
    aesdec,
    aesdeclast,
    aesenc,
    aesenclast,
    aesimc,
    aeskeygenassist,
    and_,
    andn,
    andnhm,
    andpd,
    andps,
    andnpd,
    andnps,
    arpl,
    blendpd,
    blendps,
    blendvpd,
    blendvps,
    bound,
    bsf,
    bsr,
    bswap,
    bt,
    btc,
    btr,
    bts,
    bzhi,
    call,
    callf,
    cbw,
    cdq,
    cdqe,
    clac,
    clc,
    cld,
    cldemote,
    clflush,
    clflushopt,
    clgi,
    cli,
    clts,
    clwb,
    clzero,
    cmc,
    cmovo,
    cmovno,
    cmovb,
    cmovnb,
    cmovz,
    cmovnz,
    cmovbe,
    cmovnbe,
    cmovs,
    cmovns,
    cmovp,
    cmovnp,
    cmovl,
    cmovnl,
    cmovle,
    cmovnle,
    cmp,
    cmppd,
    cmpps,
    cmps,
    cmpsb,
    cmpsw,
    cmpsd,
    cmpsq,
    cmpss,
    cmpxchg,
    cmpxchg8b,
    cmpxchg16b,
    comisd,
    comiss,
    cpuid,
    cqo,
    crc32,
    cvtdq2pd,
    cvtdq2ps,
    cvtpd2dq,
    cvtpd2pi,
    cvtpd2ps,
    cvtpi2pd,
    cvtpi2ps,
    cvtps2dq,
    cvtps2pd,
    cvtps2pi,
    cvtsd2si,
    cvtsd2ss,
    cvtsi2sd,
    cvtsi2ss,
    cvtss2sd,
    cvtss2si,
    cvttpd2dq,
    cvttpd2pi,
    cvttps2dq,
    cvttps2pi,
    cvttsd2si,
    cvttss2si,
    cwd,
    cwde,
    daa,
    das,
    dec,
    div,
    divpd,
    divps,
    divsd,
    divss,
    dppd,
    dpps,
    emms,
    enter,
    encls,
    enclu,
    enclv,
    extractps,
    f2xm1,
    fabs,
    fadd,
    faddp,
    fiadd,
    fbld,
    fbstp,
    fchs,
    fclex,
    fnclex,
    fcmovcc,
    fcom,
    fcomp,
    fcompp,
    fcomi,
    fcomip,
    fcos,
    fdecstp,
    fdiv,
    fdivp,
    fidiv,
    fdivr,
    fdivrp,
    fidivr,
    femms,
    ffree,
    ficom,
    ficomp,
    fild,
    fincstp,
    finit,
    fninit,
    fist,
    fistp,
    fisttp,
    fld,
    fld1,
    fldl2t,
    fldl2e,
    fldpi,
    fldlg2,
    fldln2,
    fldz,
    fldcw,
    fldenv,
    fmul,
    fmulp,
    fimul,
    fnop,
    fpatan,
    fprem,
    fprem1,
    fptan,
    frndint,
    frstor,
    fsave,
    fnsave,
    fscale,
    fsin,
    fsincos,
    fsqrt,
    fst,
    fstp,
    fstcw,
    fnstcw,
    fstenv,
    fnstenv,
    fstsw,
    fnstsw,
    fsub,
    fsubp,
    fisub,
    fsubr,
    fsubrp,
    fisubr,
    ftst,
    fucom,
    fucomp,
    fucompp,
    fucomi,
    fucomip,
    fwait,
    fxam,
    fxch,
    fxrstor,
    fxrstor64,
    fxsave,
    fxsave64,
    fxtract,
    fyl2x,
    fyl2xp1,
    getsec,
    haddpd,
    haddps,
    hlt,
    hsubpd,
    hsubps,
    icebp,
    idiv,
    imul,
    in,
    inc,
    ins,
    insb,
    insw,
    insd,
    insertps,
    int_,
    int3,
    into,
    invd,
    invlpg,
    invpcid,
    invvpid,
    iret,
    iretd,
    iretq,
    jo,
    jno,
    jb,
    jnb,
    jz,
    jnz,
    jbe,
    jnbe,
    js,
    jns,
    jnp,
    jp,
    jl,
    jnl,
    jle,
    jnle,
    jcxz,
    jecxz,
    jrcxz,
    jmp,
    jmpf,
    lahf,
    lar,
    lddqu,
    ldmxcsr,
    lds,
    les,
    lfs,
    lgs,
    lss,
    lea,
    leave,
    lfence,
    lgdt,
    lidt,
    lldt,
    lmsw,
    lock,
    lods,
    lodsb,
    lodsw,
    lodsd,
    lodsq,
    loop,
    loope,
    loopne,
    lsl,
    ltr,
    lzcnt,
    maskmovdqu,
    maskmovq,
    maxpd,
    maxps,
    maxsd,
    maxss,
    mfence,
    minpd,
    minps,
    minsd,
    minss,
    monitor,
    mov,
    movapd,
    movaps,
    movbe,
    movd,
    movq,
    movddup,
    movdq2q,
    movdqa,
    movdqu,
    movhlps,
    movhpd,
    movhps,
    movlhps,
    movlpd,
    movlps,
    movmskpd,
    movmskps,
    movntdqa,
    movntdq,
    movnti,
    movntpd,
    movntps,
    movntq,
    movq2dq,
    movs,
    movsb,
    movsw,
    movsd,
    movsq,
    movshdup,
    movsldup,
    movss,
    movsx,
    movsxd,
    movupd,
    movups,
    movzx,
    movsbl,
    movswl,
    movzbl,
    movzwl,
    mpsadbw,
    mul,
    mulpd,
    mulps,
    mulsd,
    mulss,
    mulx,
    mwait,
    neg,
    nop,
    not_,
    or_,
    orpd,
    orps,
    out,
    outs,
    outsb,
    outsw,
    outsd,
    pabsb,
    pabsw,
    pabsd,
    packsswb,
    packssdw,
    packuswb,
    packusdw,
    paddb,
    paddw,
    paddd,
    paddq,
    paddsb,
    paddsw,
    paddusb,
    paddusw,
    palignr,
    pand,
    pandn,
    pavgb,
    pavgw,
    pblendvb,
    pblendw,
    pclmulqdq,
    pcmpeqb,
    pcmpeqw,
    pcmpeqd,
    pcmpeqq,
    pcmpestri,
    pcmpestrm,
    pcmpgtb,
    pcmpgtw,
    pcmpgtd,
    pcmpgtq,
    pcmpistri,
    pcmpistrm,
    pdep,
    pext,
    pextrb,
    pextrd,
    pextrq,
    pextrw,
    phaddw,
    phaddd,
    phaddsw,
    phsubw,
    phsubd,
    phsubsw,
    pinsrb,
    pinsrd,
    pinsrq,
    pinsrw,
    pmaddubw,
    pmaddubsw,
    pmaddwd,
    pmaxsb,
    pmaxsw,
    pmaxsd,
    pmaxub,
    pmaxuw,
    pmaxud,
    pminsb,
    pminsw,
    pminsd,
    pminub,
    pminuw,
    pminud,
    pmovmskb,
    pmovsx,
    pmovzx,
    pmuldq,
    pmulhrsw,
    pmulhuw,
    pmulhw,
    pmulildq,
    pmulld,
    pmullw,
    pmuludq,
    pop,
    popa,
    popad,
    popcnt,
    popf,
    popfd,
    popfq,
    por,
    prefetchw,
    prefetchwt1,
    psadbw,
    pshufb,
    pshufd,
    pshufhw,
    pshuflw,
    pshufw,
    psignb,
    psignw,
    psignd,
    psllw,
    pslld,
    psllq,
    pslldq,
    psraw,
    psrad,
    psrlw,
    psrld,
    psrlq,
    psrldq,
    psubb,
    psubw,
    psubd,
    psubq,
    psubsb,
    psubsw,
    psubusb,
    psubusw,
    ptest,
    punpckhbw,
    punpckhwd,
    punpckhdq,
    punpckhqdq,
    punpcklbw,
    punpcklwd,
    punpckldq,
    punpcklqdq,
    punpchbw,
    punpchwd,
    punpchdq,
    punpchqdq,
    punpclbw,
    punpclwd,
    punpcldq,
    punpclqdq,
    push,
    pusha,
    pushad,
    pushf,
    pushfd,
    pushfq,
    pxor,
    rcl,
    rcr,
    rcpps,
    rcpss,
    rdfsbase,
    rdgsbase,
    rdmsr,
    rdpmc,
    rdrand,
    rdseed,
    rdtsc,
    rdtscp,
    rep,
    repe,
    repne,
    ret,
    retf,
    rol,
    ror,
    rorx,
    roundpd,
    roundps,
    roundsd,
    roundss,
    rsm,
    rsqrtps,
    rsqrtss,
    sahf,
    sal,
    salc,
    sar,
    sarx,
    sbb,
    scas,
    scasb,
    scasw,
    scasd,
    scasq,
    seto,
    setno,
    setb,
    setnb,
    setz,
    setnz,
    setbe,
    setnbe,
    sets,
    setns,
    setp,
    setnp,
    setl,
    setnl,
    setle,
    setnle,
    sfence,
    sgdt,
    shl,
    shld,
    shlx,
    shr,
    shrd,
    shrx,
    shufpd,
    shufps,
    sidt,
    sldt,
    smsw,
    sqrtpd,
    sqrtps,
    sqrtsd,
    sqrtss,
    stac,
    stc,
    std,
    sti,
    stmxcsr,
    stos,
    stosb,
    stosw,
    stosd,
    stosq,
    str,
    sub,
    subpd,
    subps,
    subsd,
    subss,
    swapgs,
    syscall,
    sysenter,
    sysexit,
    sysret,
    t1mskc,
    test,
    txt,
    tzcnt,
    ucomisd,
    ucomiss,
    ud1,
    ud2,
    unpckhpd,
    unpckhps,
    unpcklpd,
    unpcklps,
    verr,
    verw,
    vmptrld,
    vmptrst,
    vmread,
    vmwrite,
    wbinvd,
    wbnoinvd,
    wrfsbase,
    wrgsbase,
    wrmsr,
    xadd,
    xchg,
    xgetbv,
    xlat,
    xlatb,
    xor_,
    xorpd,
    xorps,
    xrstor,
    xrstors,
    xsave,
    xsavec,
    xsaveopt,
    xsaves,
    xsetbv,
    vmcall,
    vmlaunch,
    vmresume,
    vmxoff,
    xend,
    vmfunc,
};

enum class instruction_pair_t {
    movmskps_or_movmskpd,
    sqrtps_or_sqrtpd,
    rsqrtps_or_rsqrtss,
    rcpps_or_rcpss,
    andps_or_andpd,
    andnps_or_andnpd,
    orps_or_orpd,
    xorps_or_xorpd,
    addps_or_addpd,
    mulps_or_mulpd,
    cvtps2pd_or_cvtpd2ps,
    cvtdq2ps_or_cvtps2dq,
    subps_or_subpd,
    minps_or_minpd,
    divps_or_divpd,
    maxps_or_maxpd,
    haddpd_or_haddps,
    hsubpd_or_hsubps,
    movd_or_movq,
    movdqa_or_movdqu,
    pshufw_or_pshufdb,
    cvtpi2ps_or_cvttps2pi,
    movntps_or_movntpd,
    cvtps2pi_or_cvtpi2pd,
    cvttps2pi_or_cvttpd2pi,
    ucomiss_or_ucomisd,
    comiss_or_comisd,
    movups_or_movupd,
    movlps_or_movlpd,
    unpcklps_or_unpcklpd,
    unpckhps_or_unpckhpd,
    movhps_or_movhpd,
    loadall_or_syscall,
    cmpps_or_cmppd,
    shufps_or_shufpd,
    addsubpd_or_addsubps,
    cvttpd2dq_or_cvtpi2pd,
    pinsrd_or_pinsrq,
    pextrd_or_pextrq,
    maskmovq_or_maskmovdqu,
    wait_or_fwait
};

enum class legacy_prefix_t : uint8_t {
    // 1 byte
    // group 1
    lock = 0xf0,
    repne = 0xf2,
    rep = 0xf3,
    // group 2
    cs_seg_override = 0x2e,
    ss_seg_override = 0x36,
    ds_seg_override = 0x3e,
    es_seg_override = 0x26,
    fs_seg_override = 0x64,
    gs_seg_override = 0x65,
    branch_not_taken = 0x2e,
    branch_taken = 0x3e,
    // group 3
    operand_size_override = 0x66,
    // group 4
    address_size_override = 0x67,
    // rex
    rex_prefix_range_min = 0x40, // rex is for x64 only
    rex_prefix_range_max = 0x4f
};

enum class register_encoding_t : uint8_t {
    // 3 bits
    // 32bit, 64bit, 16bit, 8bit(high/low -> rex prefix)
    eax = 0, // eax, rax, ax, al
    ecx = 1, // ecx, rcx, cx, cl
    edx = 2, // edx, rdx, dx, dl
    ebx = 3, // ebx, rbx, bx, bl
    esp = 4, // esp, rsp, sp, ah/spl
    ebp = 5, // ebp, rbp, bp, ch/bpl
    esi = 6, // esi, rsi, si, dh/sil
    edi = 7, // edi, rdi, di, bh/dil
};

enum class extended_register_encoding_t : uint8_t {
    // only x86-64, 4 bits
    rax = 0,
    rcx = 1,
    rdx = 2,
    rbx = 3,
    rsp = 4,
    rbp = 5,
    rsi = 6,
    rdi = 7,
    r8 = 8,
    r9 = 9,
    r10 = 10,
    r11 = 11,
    r12 = 12,
    r13 = 13,
    r14 = 14,
    r15 = 15,
};

enum class segment_register_encoding_t : uint8_t {
    // 3 bits
    es = 0,
    cs = 1,
    ss = 2,
    ds = 3,
    fs = 4,
    gs = 5,
};

enum class control_register_encoding_t : uint8_t {
    // 4 bits
    cr0 = 0,
    cr2 = 2,
    cr3 = 3,
    cr4 = 4,
    cr8 = 8
};

enum class mod_type_t : uint8_t {
    // 2 bits
    memory_no_disp = 0,
    memory_short_disp = 1,
    memory_long_disp = 2,
    register_ = 3
};

enum class sib_scale_t : uint8_t {
    // 2 bits
    mult_1 = 0b00,
    mult_2 = 0b01,
    mult_4 = 0b10,
    mult_8 = 0b11,
};

enum class opcode_family_t {
    primary = 0,
    extended_2byte,
    extended_3byte_1,
    extended_3byte_2,
    fpu,
    vex_2byte,
    vex_3byte,
    evex,
};

enum class opcode_group_t {
    group1,
    group2,
    group3,
    group4,
    group5,
    group6,
    group7,
    group8,
    group9,
    group11,
    group12,
    group13,
    group14,
    group15,
    group16,
    group_nop
};

static constexpr uint8_t rex_prefix_range_min = 0x40; // rex is for x64 only
static constexpr uint8_t rex_prefix_range_max = 0x4f;

static constexpr auto modrm_use_sib = 4; // when mod is memory
static constexpr auto modrm_use_rip_relative = 5; // when mod=0

static constexpr auto sib_no_base_reg = register_encoding_t::ebp; // only if modr/m is 0
static constexpr auto sib_no_index_reg = register_encoding_t::esp;

static constexpr auto opcode_escape_2byte = 0x0f;
static constexpr auto opcode_escape_3byte_1 = 0x38; // 0x0f 0x38
static constexpr auto opcode_escape_3byte_2 = 0x3a; // 0x0f 0x3a
static constexpr auto opcode_fpumap_range_min = 0xd8;
static constexpr auto opcode_fpumap_range_max = 0xdf;
static constexpr auto opcode_escape_vexmap_1 = 0xc4; // 2 bytes
static constexpr auto opcode_escape_vexmap_2 = 0xc5; // 3 bytes
static constexpr auto opcode_escape_evexmap = 0x62;

enum class repeat_type_t : uint8_t {
    none = 0,
    rep,
    repne
};

enum class segment_override_t : uint8_t {
    none = 0,
    cs,
    ds,
    ss,
    es,
    fs,
    gs
};

enum class branch_hint_t : uint8_t {
    none = 0,
    taken,
    not_taken,
};

// todo: separate into different enums: control, debug, segment, general?
enum class register_t {
    al, ah, ax, eax, rax,
    bl, bh, bx, ebx, rbx,
    cl, ch, cx, ecx, rcx,
    dl, dh, dx, edx, rdx,
    spl, sp, esp, rsp,
    bpl, bp, ebp, rbp,
    sil, si, esi, rsi,
    dil, di, edi, rdi,
    ip, eip, rip,
    r8b, r8w, r8d, r8,
    r9b, r9w, r9d, r9,
    r10b, r10w, r10d, r10,
    r11b, r11w, r11d, r11,
    r12b, r12w, r12d, r12,
    r13b, r13w, r13d, r13,
    r14b, r14w, r14d, r14,
    r15b, r15w, r15d, r15,
    cs, ds, es, fs, gs, ss
};

enum class addressing_size_t {
    byte,
    word,
    dword,
    qword
};

#pragma pack(push, 1)

struct rex_prefix_t {
    union {
        struct {
            uint8_t base : 1;
            uint8_t index : 1;
            uint8_t reg : 1;
            uint8_t width : 1;
            uint8_t reserved0 : 4;
        } bits;
        uint8_t raw;
    };
};

struct mod_rm_t {
    // when mod is memory
    //  reg/opcode = standard register
    //  r/m = standard register containing base address [0x5 means rip relative (64bit) or 32 bit displacement]
    //      special values
    //          r/m = 4 -> use SIB byte for addressing
    //          r/m = 5 (mod=0) do rip relative (in 64bit) or 32 bit displacement
    union {
        struct {
            uint8_t rm : 3;
            uint8_t reg_opcode : 3;
            mod_type_t mod : 2;
        } bits;
        uint8_t raw;
    };
};

struct sib_t {
    union {
        struct {
            register_encoding_t base : 3;
            register_encoding_t index : 3;
            sib_scale_t scale : 2;
        };
        uint8_t raw;
    };
};

#pragma pack(pop)

const char* get_instruction_mnemonic(instruction_t instruction);
instruction_t translate_instruction_pair(instruction_pair_t pair);

register_t translate_register(register_encoding_t encoding, addressing_size_t size);
register_t translate_register(extended_register_encoding_t encoding, addressing_size_t size);
register_t translate_byte_rex_modified_register(register_encoding_t encoding);
const char* get_register_name(register_t register_);

}
