
#include "x86/opcode.h"

namespace x86::opcode {

static const char* instruction_names[] = {
    "aaa",
    "aad",
    "aam",
    "aas",
    "adc",
    "adcx",
    "add",
    "addpd",
    "addps",
    "addsd",
    "addss",
    "addsubpd",
    "addsubps",
    "adox",
    "aesdec",
    "aesdeclast",
    "aesenc",
    "aesenclast",
    "aesimc",
    "aeskeygenassist",
    "and",
    "andn",
    "andnhm",
    "andpd",
    "andps",
    "andnpd",
    "andnps",
    "arpl",
    "blendpd",
    "blendps",
    "blendvpd",
    "blendvps",
    "bound",
    "bsf",
    "bsr",
    "bswap",
    "bt",
    "btc",
    "btr",
    "bts",
    "bzhi",
    "call",
    "callf",
    "cbw",
    "cdq",
    "cdqe",
    "clac",
    "clc",
    "cld",
    "cldemote",
    "clflush",
    "clflushopt",
    "clgi",
    "cli",
    "clts",
    "clwb",
    "clzero",
    "cmc",
    "cmovo",
    "cmovno",
    "cmovb",
    "cmovnb",
    "cmovz",
    "cmovnz",
    "cmovbe",
    "cmovnbe",
    "cmovs",
    "cmovns",
    "cmovp",
    "cmovnp",
    "cmovl",
    "cmovnl",
    "cmovle",
    "cmovnle",
    "cmp",
    "cmppd",
    "cmpps",
    "cmps",
    "cmpsb",
    "cmpsw",
    "cmpsd",
    "cmpsq",
    "cmpss",
    "cmpxchg",
    "cmpxchg8b",
    "cmpxchg16b",
    "comisd",
    "comiss",
    "cpuid",
    "cqo",
    "crc32",
    "cvtdq2pd",
    "cvtdq2ps",
    "cvtpd2dq",
    "cvtpd2pi",
    "cvtpd2ps",
    "cvtpi2pd",
    "cvtpi2ps",
    "cvtps2dq",
    "cvtps2pd",
    "cvtps2pi",
    "cvtsd2si",
    "cvtsd2ss",
    "cvtsi2sd",
    "cvtsi2ss",
    "cvtss2sd",
    "cvtss2si",
    "cvttpd2dq",
    "cvttpd2pi",
    "cvttps2dq",
    "cvttps2pi",
    "cvttsd2si",
    "cvttss2si",
    "cwd",
    "cwde",
    "daa",
    "das",
    "dec",
    "div",
    "divpd",
    "divps",
    "divsd",
    "divss",
    "dppd",
    "dpps",
    "emms",
    "enter",
    "encls",
    "enclu",
    "enclv",
    "extractps",
    "f2xm1",
    "fabs",
    "fadd",
    "faddp",
    "fiadd",
    "fbld",
    "fbstp",
    "fchs",
    "fclex",
    "fnclex",
    "fcmovcc",
    "fcom",
    "fcomp",
    "fcompp",
    "fcomi",
    "fcomip",
    "fcos",
    "fdecstp",
    "fdiv",
    "fdivp",
    "fidiv",
    "fdivr",
    "fdivrp",
    "fidivr",
    "femms",
    "ffree",
    "ficom",
    "ficomp",
    "fild",
    "fincstp",
    "finit",
    "fninit",
    "fist",
    "fistp",
    "fisttp",
    "fld",
    "fld1",
    "fldl2t",
    "fldl2e",
    "fldpi",
    "fldlg2",
    "fldln2",
    "fldz",
    "fldcw",
    "fldenv",
    "fmul",
    "fmulp",
    "fimul",
    "fnop",
    "fpatan",
    "fprem",
    "fprem1",
    "fptan",
    "frndint",
    "frstor",
    "fsave",
    "fnsave",
    "fscale",
    "fsin",
    "fsincos",
    "fsqrt",
    "fst",
    "fstp",
    "fstcw",
    "fnstcw",
    "fstenv",
    "fnstenv",
    "fstsw",
    "fnstsw",
    "fsub",
    "fsubp",
    "fisub",
    "fsubr",
    "fsubrp",
    "fisubr",
    "ftst",
    "fucom",
    "fucomp",
    "fucompp",
    "fucomi",
    "fucomip",
    "fwait",
    "fxam",
    "fxch",
    "fxrstor",
    "fxrstor64",
    "fxsave",
    "fxsave64",
    "fxtract",
    "fyl2x",
    "fyl2xp1",
    "getsec",
    "haddpd",
    "haddps",
    "hlt",
    "hsubpd",
    "hsubps",
    "icebp",
    "idiv",
    "imul",
    "in",
    "inc",
    "ins",
    "insb",
    "insw",
    "insd",
    "insertps",
    "int",
    "int3",
    "into",
    "invd",
    "invlpg",
    "invpcid",
    "invvpid",
    "iret",
    "iretd",
    "iretq",
    "jo",
    "jno",
    "jb",
    "jnb",
    "jz",
    "jnz",
    "jbe",
    "jnbe",
    "js",
    "jns",
    "jnp",
    "jp",
    "jl",
    "jnl",
    "jle",
    "jnle",
    "jcxz",
    "jecxz",
    "jrcxz",
    "jmp",
    "jmpf",
    "lahf",
    "lar",
    "lddqu",
    "ldmxcsr",
    "lds",
    "les",
    "lfs",
    "lgs",
    "lss",
    "lea",
    "leave",
    "lfence",
    "lgdt",
    "lidt",
    "lldt",
    "lmsw",
    "lock",
    "lods",
    "lodsb",
    "lodsw",
    "lodsd",
    "lodsq",
    "loop",
    "loope",
    "loopne",
    "lsl",
    "ltr",
    "lzcnt",
    "maskmovdqu",
    "maskmovq",
    "maxpd",
    "maxps",
    "maxsd",
    "maxss",
    "mfence",
    "minpd",
    "minps",
    "minsd",
    "minss",
    "monitor",
    "mov",
    "movapd",
    "movaps",
    "movbe",
    "movd",
    "movq",
    "movddup",
    "movdq2q",
    "movdqa",
    "movdqu",
    "movhlps",
    "movhpd",
    "movhps",
    "movlhps",
    "movlpd",
    "movlps",
    "movmskpd",
    "movmskps",
    "movntdqa",
    "movntdq",
    "movnti",
    "movntpd",
    "movntps",
    "movntq",
    "movq2dq",
    "movs",
    "movsb",
    "movsw",
    "movsd",
    "movsq",
    "movshdup",
    "movsldup",
    "movss",
    "movsx",
    "movsxd",
    "movupd",
    "movups",
    "movzx",
    "movsbl",
    "movswl",
    "movzbl",
    "movzwl",
    "mpsadbw",
    "mul",
    "mulpd",
    "mulps",
    "mulsd",
    "mulss",
    "mulx",
    "mwait",
    "neg",
    "nop",
    "not",
    "or",
    "orpd",
    "orps",
    "out",
    "outs",
    "outsb",
    "outsw",
    "outsd",
    "pabsb",
    "pabsw",
    "pabsd",
    "packsswb",
    "packssdw",
    "packuswb",
    "packusdw",
    "paddb",
    "paddw",
    "paddd",
    "paddq",
    "paddsb",
    "paddsw",
    "paddusb",
    "paddusw",
    "palignr",
    "pand",
    "pandn",
    "pavgb",
    "pavgw",
    "pblendvb",
    "pblendw",
    "pclmulqdq",
    "pcmpeqb",
    "pcmpeqw",
    "pcmpeqd",
    "pcmpeqq",
    "pcmpestri",
    "pcmpestrm",
    "pcmpgtb",
    "pcmpgtw",
    "pcmpgtd",
    "pcmpgtq",
    "pcmpistri",
    "pcmpistrm",
    "pdep",
    "pext",
    "pextrb",
    "pextrd",
    "pextrq",
    "pextrw",
    "phaddw",
    "phaddd",
    "phaddsw",
    "phsubw",
    "phsubd",
    "phsubsw",
    "pinsrb",
    "pinsrd",
    "pinsrq",
    "pinsrw",
    "pmaddubw",
    "pmaddubsw",
    "pmaddwd",
    "pmaxsb",
    "pmaxsw",
    "pmaxsd",
    "pmaxub",
    "pmaxuw",
    "pmaxud",
    "pminsb",
    "pminsw",
    "pminsd",
    "pminub",
    "pminuw",
    "pminud",
    "pmovmskb",
    "pmovsx",
    "pmovzx",
    "pmuldq",
    "pmulhrsw",
    "pmulhuw",
    "pmulhw",
    "pmulildq",
    "pmulld",
    "pmullw",
    "pmuludq",
    "pop",
    "popa",
    "popad",
    "popcnt",
    "popf",
    "popfd",
    "popfq",
    "por",
    "prefetchw",
    "prefetchwt1",
    "psadbw",
    "pshufb",
    "pshufd",
    "pshufhw",
    "pshuflw",
    "pshufw",
    "psignb",
    "psignw",
    "psignd",
    "psllw",
    "pslld",
    "psllq",
    "pslldq",
    "psraw",
    "psrad",
    "psrlw",
    "psrld",
    "psrlq",
    "psrldq",
    "psubb",
    "psubw",
    "psubd",
    "psubq",
    "psubsb",
    "psubsw",
    "psubusb",
    "psubusw",
    "ptest",
    "punpckhbw",
    "punpckhwd",
    "punpckhdq",
    "punpckhqdq",
    "punpcklbw",
    "punpcklwd",
    "punpckldq",
    "punpcklqdq",
    "punpchbw",
    "punpchwd",
    "punpchdq",
    "punpchqdq",
    "punpclbw",
    "punpclwd",
    "punpcldq",
    "punpclqdq",
    "push",
    "pusha",
    "pushad",
    "pushf",
    "pushfd",
    "pushfq",
    "pxor",
    "rcl",
    "rcr",
    "rcpps",
    "rcpss",
    "rdfsbase",
    "rdgsbase",
    "rdmsr",
    "rdpmc",
    "rdrand",
    "rdseed",
    "rdtsc",
    "rdtscp",
    "rep",
    "repe",
    "repne",
    "ret",
    "retf",
    "rol",
    "ror",
    "rorx",
    "roundpd",
    "roundps",
    "roundsd",
    "roundss",
    "rsm",
    "rsqrtps",
    "rsqrtss",
    "sahf",
    "sal",
    "salc",
    "sar",
    "sarx",
    "sbb",
    "scas",
    "scasb",
    "scasw",
    "scasd",
    "scasq",
    "seto",
    "setno",
    "setb",
    "setnb",
    "setz",
    "setnz",
    "setbe",
    "setnbe",
    "sets",
    "setns",
    "setp",
    "setnp",
    "setl",
    "setnl",
    "setle",
    "setnle",
    "sfence",
    "sgdt",
    "shl",
    "shld",
    "shlx",
    "shr",
    "shrd",
    "shrx",
    "shufpd",
    "shufps",
    "sidt",
    "sldt",
    "smsw",
    "sqrtpd",
    "sqrtps",
    "sqrtsd",
    "sqrtss",
    "stac",
    "stc",
    "std",
    "sti",
    "stmxcsr",
    "stos",
    "stosb",
    "stosw",
    "stosd",
    "stosq",
    "str",
    "sub",
    "subpd",
    "subps",
    "subsd",
    "subss",
    "swapgs",
    "syscall",
    "sysenter",
    "sysexit",
    "sysret",
    "t1mskc",
    "test",
    "txt",
    "tzcnt",
    "ucomisd",
    "ucomiss",
    "ud1",
    "ud2",
    "unpckhpd",
    "unpckhps",
    "unpcklpd",
    "unpcklps",
    "verr",
    "verw",
    "vmptrld",
    "vmptrst",
    "vmread",
    "vmwrite",
    "wbinvd",
    "wbnoinvd",
    "wrfsbase",
    "wrgsbase",
    "wrmsr",
    "xadd",
    "xchg",
    "xgetbv",
    "xlat",
    "xlatb",
    "xor",
    "xorpd",
    "xorps",
    "xrstor",
    "xrstors",
    "xsave",
    "xsavec",
    "xsaveopt",
    "xsaves",
    "xsetbv"
};


static register_t register_encoding[][4] = {
    { register_t::al, register_t::ax, register_t::eax, register_t::rax },
    { register_t::cl, register_t::cx, register_t::ecx, register_t::rcx },
    { register_t::dl, register_t::dx, register_t::edx, register_t::rdx },
    { register_t::bl, register_t::bx, register_t::eax, register_t::rax },
    { register_t::ah, register_t::sp, register_t::esp, register_t::rsp },
    { register_t::ch, register_t::bp, register_t::ebp, register_t::rbp },
    { register_t::dh, register_t::si, register_t::esi, register_t::rsi },
    { register_t::bh, register_t::di, register_t::edi, register_t::rdi },
};

static register_t register_extended_encoding[][4] = {
    { register_t::r8b, register_t::r8w, register_t::r8d, register_t::r8 },
    { register_t::r9b, register_t::r9w, register_t::r9d, register_t::r9 },
    { register_t::r10b, register_t::r10w, register_t::r10d, register_t::r10 },
    { register_t::r11b, register_t::r11w, register_t::r11d, register_t::r11 },
    { register_t::r12b, register_t::r12w, register_t::r12d, register_t::r12 },
    { register_t::r13b, register_t::r13w, register_t::r13d, register_t::r13 },
    { register_t::r14b, register_t::r14w, register_t::r14d, register_t::r14 },
    { register_t::r15b, register_t::r15w, register_t::r15d, register_t::r15 },
};

static const char* register_names[] = {
    "al", "ah", "ax", "eax", "rax",
    "bl", "bh", "bx", "ebx", "rbx",
    "cl", "ch", "cx", "ecx", "rcx",
    "dl", "dh", "dx", "edx", "rdx",
    "spl", "sp", "esp", "rsp",
    "bpl", "bp", "ebp", "rbp",
    "sil", "si", "esi", "rsi",
    "dil", "di", "edi", "rdi",
    "ip", "eip", "rip",
    "r8b", "r8w", "r8d", "r8",
    "r9b", "r9w", "r9d", "r9",
    "r10b", "r10w", "r10d", "r10",
    "r11b", "r11w", "r11d", "r11",
    "r12b", "r12w", "r12d", "r12",
    "r13b", "r13w", "r13d", "r13",
    "r14b", "r14w", "r14d", "r14",
    "r15b", "r15w", "r15d", "r15",
    "cs", "ds", "es", "fs", "gs", "ss"
};

constexpr auto last_instruction = instruction_t::xsetbv;
constexpr auto last_register = register_t::ss;
constexpr auto last_register_encoding = register_encoding_t::edi;
constexpr auto last_ext_register_encoding = extended_register_encoding_t::r15;
constexpr auto last_addressing_size = addressing_size_t::qword;


const char* get_instruction_mnemonic(const instruction_t instruction) {
    static_assert(static_cast<size_t>(last_instruction) == array_size(instruction_names) - 1, "instruction_names table missing rows");
    return instruction_names[static_cast<size_t>(instruction)];
}

instruction_t translate_instruction_pair(const instruction_pair_t pair) {
    return instruction_t::aaa; // todo:
}

register_t translate_register(const register_encoding_t encoding, const addressing_size_t size) {
    static_assert(static_cast<size_t>(last_register_encoding) == array_size(register_encoding) - 1, "register_encoding table missing rows");
    static_assert(static_cast<size_t>(last_addressing_size) == array_size(register_encoding[0]) - 1, "register_encoding table missing columns");
    return register_encoding[static_cast<size_t>(encoding)][static_cast<size_t>(size)];
}

register_t translate_register(const extended_register_encoding_t encoding, const addressing_size_t size) {
    if (encoding < extended_register_encoding_t::r8) {
        return translate_register(static_cast<register_encoding_t>(encoding), size);
    }

    static_assert(static_cast<size_t>(last_ext_register_encoding) - static_cast<size_t>(extended_register_encoding_t::r8) == array_size(register_extended_encoding) - 1, "register_extended_encoding table missing rows");
    static_assert(static_cast<size_t>(last_addressing_size) == array_size(register_extended_encoding[0]) - 1, "register_extended_encoding table missing columns");
    return register_extended_encoding[static_cast<size_t>(encoding) - static_cast<size_t>(extended_register_encoding_t::r8)][static_cast<size_t>(size)];
}

register_t translate_byte_rex_modified_register(const register_encoding_t encoding) {
    switch (encoding) {
        case register_encoding_t::eax:
            return register_t::al;
        case register_encoding_t::ecx:
            return register_t::cl;
        case register_encoding_t::edx:
            return register_t::dl;
        case register_encoding_t::ebx:
            return register_t::bl;
        case register_encoding_t::esp:
            return register_t::spl;
        case register_encoding_t::ebp:
            return register_t::bpl;
        case register_encoding_t::esi:
            return register_t::sil;
        case register_encoding_t::edi:
            return register_t::dil;
        default:
            __builtin_unreachable();
    }
}

const char* get_register_name(const register_t register_) {
    static_assert(static_cast<size_t>(last_register) == array_size(register_names) - 1, "register_names table missing entries");
    if (static_cast<size_t>(register_) >= array_size(register_names)) {
        return "";
    }
    return register_names[static_cast<size_t>(register_)];
}

}
